### PR TITLE
Bump Golang to 1.10.3

### PR DESCRIPTION
**Pull request by danail-branekov**
Bump Golang to 1.10.3 (currently latest)

### CODE REVIEW

**Review by craigfurman — APPROVED** [review]
LGTM 🏅

**Comment by craigfurman** [comment]
@danail-branekov good to hear from you again! This project is a ghost town for me, does one of you want to be a maintainer?

**Comment by danail-branekov** [comment]
Hey, Craig,

I have forked the repo into [masters-of-cats](https://github.com/masters-of-cats/linux-playground). We will be happy to take over the project maintenance.

**Comment by craigfurman** [comment]
I think that makes the most sense, enjoy!

**Pull request merged**
